hydra:
  run:
    dir: ./experiments_dcc_hmc/${name}/${hydra.job.override_dirname}/seed=${seed}
  sweep:
    dir: ./experiments_dcc_hmc/${name}/${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        item_sep: '_'
        exclude_keys:
          - seed
          - name

defaults:
  # - launcher: slurm
  - dataset: california
  # - override hydra/launcher: submitit_slurm

name: test_dcc_hmc
seed: 0

model: "lin_reg"

dcc_hmc:
  _target_: models.pyro_extensions.dcc_hmc.DCCHMC
  num_parallel: 1
  num_mcmc: 200
  num_slp_samples: 5
  max_slps: null
  enumerate_branches: True
  num_chains: 1
  num_mcmc_warmup: 200
  max_stacked: null
  beta: !!float inf